# Copyright (c) 2021 Enix, SAS
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing
# permissions and limitations under the License.
#
# Authors:
# Paul Laffitte <paul.laffitte@enix.fr>
# Arthur Chaloin <arthur.chaloin@enix.fr>
# Alexandre Buisine <alexandre.buisine@enix.fr>

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jobclaim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: my-marvelous-storage
  resources:
    requests:
      storage: 100Gi
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: read-write-a
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          nodeSelector:
            id: "1"
          containers:
          - image: alpine
            name: read-write-a
            args:
            - sh
            - -c
            - 'ls -la /vol > /vol/ls-$(date +%s) && cat /vol/* | head -n 1000 > /vol/cat-$(date +%s)'
            volumeMounts:
            - mountPath: /vol
              name: volume
          volumes:
          - name: volume
            persistentVolumeClaim:
              claimName: jobclaim
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: read-write-b
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          nodeSelector:
            id: "2"
          containers:
          - image: alpine
            name: read-write-b
            args:
            - sh
            - -c
            - 'ls -la /vol > /vol/ls-$(date +%s) && cat /vol/* | head -n 1000 > /vol/cat-$(date +%s)'
            volumeMounts:
            - mountPath: /vol
              name: volume
          volumes:
          - name: volume
            persistentVolumeClaim:
              claimName: jobclaim
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: read-write-c
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          nodeSelector:
            id: "3"
          containers:
          - image: alpine
            name: read-write-c
            args:
            - sh
            - -c
            - 'ls -la /vol > /vol/ls-$(date +%s) && cat /vol/* | head -n 1000 > /vol/cat-$(date +%s)'
            volumeMounts:
            - mountPath: /vol
              name: volume
          volumes:
          - name: volume
            persistentVolumeClaim:
              claimName: jobclaim
